name: "Build PHP 8.5"

on:
  push:
    branches: [ci/php-85-build]

jobs:
  build:
    name: "PHP 8.5 ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [linux-x86_64, linux-aarch64, macos-x86_64, macos-aarch64]
    uses: ./.github/workflows/build-unix.yml
    with:
      os: ${{ matrix.os }}
      php-version: '8.5'
      extensions: "bcmath,openssl,tokenizer,curl,phar,filter,mbstring,ctype,dom,libxml,simplexml"
      build-cli: false
      build-micro: true
      prefer-pre-built: true
